#!/usr/bin/env bash

function intall_naylib(){
  cd
  git clone https://github.com/Federico-Ciuffardi/naylib.git
  cd naylib
  sudo make install
  cd ..
  rm -rf naylib
}

while true ; do
  printf "1-Arch\n2-Ubuntu\n3-Termux\nEnter current distro: "
  read awns
  case $awns in
    1)
      yay -Q "lsb-release" &> /dev/null || sudo pacman -S lsb-release
      intall_naylib
      exit 0
      ;;
    2)
      sudo apt update
      dpkg -s "$$" &>/dev/null || sudo apt install lsb-release
      intall_naylib
      exit 0
      ;;
    3)
      dpkg -s "proot" &>/dev/null || pkg install proot
      printf '#!/bin/bash\n[ "$@" = "-v" ] || $@' > /bin/sudo # fake sudo
      chmod +x /bin/sudo
      intall_naylib
      termux-chroot
      exit 0
      ;;
    *)
      printf "Invalid awns\n"
      ;;
  esac
done
