#!/usr/bin/env bash

function intall_naylib(){
  cd
  git clone https://github.com/Federico-Ciuffardi/naylib.git
  cd naylib
  sudo make install
  cd ..
  rm -rf naylib
}

while true ; do
  printf "1-Arch\n2-Ubuntu\n3-Termux\n4-Just install (not recommended)\nEnter current distro: "
  read awns
  case $awns in
    1)
      yay -Q "lsb-release" &> /dev/null || sudo pacman -S lsb-release
      intall_naylib
      exit 0
      ;;
    2)
      sudo apt update
      dpkg -s "lsb-release" &>/dev/null || sudo apt install lsb-release
      dpkg -s "make" &>/dev/null || sudo apt install make
      intall_naylib
      exit 0
      ;;
    3)
      dpkg -s "proot" &>/dev/null || pkg install proot
      printf '#!/bin/bash\necho "Termux"' > /bin/lsb_release # fake lsb_release
      chmod +x /bin/lsb_release
      printf '#!/bin/bash\n[ "$1" = "-v" ] || $@' > /bin/sudo # fake sudo
      chmod +x /bin/sudo
      intall_naylib
      termux-chroot
      exit 0
      ;;
    4)
      exit 0
      ;;
    *)
      printf "Invalid awns\n"
      ;;
  esac
done
