#!/usr/bin/env bash

source "/usr/lib/naylib"
source "/etc/lsb-release"

function install(){
  package="$1"
  package_realpath="$(realpath $package)"

  # go to data/bin/build path
  cd "$uur_data_path"
  mkdir -p "$package"
  cd "$package"

  # install package dependencies
  ! [ -f "$package_realpath/${DISTRIB_ID}Deps" ] \
  || draw_spinner "Installing \"$package\" dependencies" "bash "$package_realpath/${DISTRIB_ID}Deps"" \
  || exit 1

  # install package
  draw_spinner "Installing \"$package\"" "bash "$package_realpath/make""

  # go back to scriptpath
  cd "$SCRIPTPATH"
}

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

uur_data_path="$HOME/.local/share/uur"

mkdir -p "$uur_data_path"
cd "$SCRIPTPATH"

case $1 in
  list)
    ls -d */ | sed 's#/##g'
    ;;
  all)
    packages=($(ls))
    for package in "${packages[@]}" ; do
      [ -d "$package" ] || continue
      install "$package"
    done
    ;;
  install)
    sudo -v
    install "$2"
    ;;
esac
