#!/usr/bin/env bash

set -o errexit      # Exit on most errors (see the manual)
set -o nounset      # Disallow expansion of unset variables
set -o pipefail     # Use last non-zero exit code in a pipeline
set -o errtrace     # Ensure the error trap handler is inherited

# install nativifier
npm list -g nativefier || sudo npm install -g nativefier
npm update nativefier

git clone https://aur.archlinux.org/youtubemusic-nativefier.git || true

cd youtubemusic-nativefier

git pull

pwd

nativefier \
  --name "YouTube Music" \
  --icon "youtubemusic-nativefier.png" \
  --width "800px" \
  --height "600px" \
  --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0' \
  --verbose \
  --single-instance \
  --internal-urls ".*accounts.google.com.*|.*youtube.com.*" \
  "https://music.youtube.com"
  # --tray \

sudo ln -sf $(pwd)/YouTubeMusic-linux-x64/YouTubeMusic /bin/youtubemusic-nativefier
